config/routes.rb
Rails.application.routes.draw do
  resources :lessons
  devise_for :users
  resources :courses
  resources :users, only: %i[index edit update show]
  get 'home/activity'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  include PublicActivity::Model
  # tracked
  tracked owner: proc { |controller, _model| controller.current_user }

  LANGUAGES = %w[English Russian Polish].freeze
  LEVELS = %w[Beginner Intermediate Advanced].freeze
  class << self
    def languages
      LANGUAGES.map { |language| [language, language] }
    end

    def levels
      LEVELS.map { |level| [level, level] }
    end
  end
  belongs_to :user
  has_many :lessons, dependent: :destroy

  validates :title, :short_description, :language, :price, :level, presence: true
  validates :description, presence: true, length: { minimum: 5 }

  def to_s
    title
  end

  has_rich_text :description

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  extend FriendlyId
  include PublicActivity::Model
  belongs_to :course

  validates :title, :content, :course, presence: true

  friendly_id :title, use: :slugged
  tracked owner: proc { |controller, _model| controller.current_user }

  has_rich_text :content

  def to_s
    title
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify

  validates :name, presence: true
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  rolify

  has_many :courses

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  after_create :assign_default_role

  validate :must_have_a_role, on: :update

  friendly_id :email, use: :slugged

  def to_s
    username
  end

  def username
    email.split(/@/).first
  end

  def assign_default_role
    if User.count == 1
      add_role(:admin) if roles.blank?
      add_role(:teacher)
      add_role(:student)
    else
      add_role(:student)
      add_role(:teacher)
    end
  end

  def online?
    updated_at > 10.minutes.ago
  end

  private

  def must_have_a_role
    errors.add(:roles, 'must have at least one role') unless roles.any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include PublicActivity::StoreController
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :authenticate_user!
  before_action :set_global_variables, if: :user_signed_in?

  after_action :user_activity

  def set_global_variables
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
  end

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end

  def user_activity
    current_user.try :touch
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]

  # GET /courses or /courses.json
  def index
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
    @courses = @ransack_courses.result.includes(:user)
  end

  # GET /courses/1 or /courses/1.json
  def show
    @lessons = @course.lessons
  end

  # GET /courses/new
  def new
    @course = Course.new
    authorize @course
  end

  # GET /courses/1/edit
  def edit
    authorize @course
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params.merge({ user: current_user }))
    authorize @course

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    authorize @course
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:title, :description, :short_description, :price, :language, :level)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @courses = Course.all.limit(3)
    @latest_courses = Course.all.limit(3).order created_at: :desc
  end

  def activity
    @activities = PublicActivity::Activity.order created_at: :desc
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[show edit update destroy]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show; end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    @course = Course.friendly.find(params[:course_id])
    @lesson.course = @course
    authorize @lesson
  end

  # GET /lessons/1/edit
  def edit
    authorize @lesson
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    authorize @lesson

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    authorize @lesson
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    authorize @lesson
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lesson
    @lesson = Lesson.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lesson_params
    params.require(:lesson).permit(:title, :content, :course_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to users_path, notice: "User #{@user.email} was successfully updated"
    else
      render :edit
    end
  end

  def show; end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
    params.require(:user).permit({ role_ids: [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.haml
.card.h-100
  .card-header
    .fa.fa-graduation-cap
    = link_to course.title, course_path(course)
  .card-body
    = course.description
    %small= simple_format course.short_description
  .card-footer
    .fa.fa-globe-africa
    = course.language
    .fa.fa-signal
    = course.level
  .card-footer
    = number_to_currency course.price
  .card-footer
    .fa.fa-book
    = course.lessons.count
  .card-footer
    .far.fa-clock
    = course.created_at.strftime('%d-%b-%Y')
    .row
    .fa.fa-chalkboard-teacher
    = course.user
  - if current_user
    - if policy(course).edit?
      .card-footer
        = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-secondary'
        = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/courses/_form.html.haml
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :description
    = f.rich_text_area :description
    = f.input :short_description
    = f.input :language, collection: Course.languages, include_blank: true
    = f.input :level, collection: Course.levels, include_blank: true
    = f.input :price

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
.card
  .card-header
    %h1 New course
  .card-body
    = render 'form'
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h3
  .text-center.m-3
    Courses
    .badge.bg-danger
      = @courses.count

.row.gx-2
  .col-2
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      = f.label :title
      .mb-3= f.search_field :title_cont, placeholder: 'title', class: 'form-control'
      = f.label :short_description
      .mb-3= f.search_field :short_description_cont, placeholder: 'Short description', class: 'form-control'
      = f.label :language
      .mb-3= f.select :language_cont, Course.languages
      = f.label :level
      .mb-3= f.select :level_cont, Course.levels
      = f.label :price
      .mb-3= f.search_field :price_eq, placeholder: 'Price', class: 'form-control'
      = f.label :email
      .mb-3= f.search_field :user_email_cont, placeholder: 'User email', class: 'form-control'
      = f.submit 'search', { class: 'btn btn-primary w-100 mb-2' }
    = link_to courses_path, class: 'btn btn-secondary' do
      .fa.fa-sync
  .col-10
    .row.row-cols-1-row-cols-md-3.g-4
      - @courses.each do |course|
        .col-4
          = render 'courses/course', course: course

app/views/courses/new.html.haml
.card
  .card-header
    %h1 New course
  .card-body
    = render 'form'
= link_to 'Back', courses_path

app/views/courses/show.html.haml
= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)

.row.mt-5
  .col
    = render 'courses/course', course: @course
  .col
    = link_to 'Add lesson', new_lesson_path(course_id: @course.id)

    - @lessons.each do |lesson|
      = render 'lessons/lesson', lesson: lesson

app/views/home/activity.html.haml
%h3
  .text-center.m-3
    Activity
    .badge.bg-danger
      = @activities.count

- @activities.each do |activity|
  %ul.list-group
    %li.list-group-item= activity.id
    %li.list-group-item= activity.trackable_type
    %li.list-group-item= activity.trackable_id
    %li.list-group-item= link_to activity.trackable, activity.trackable
    %li.list-group-item= activity.key
    %li.list-group-item= activity.parameters
    %li.list-group-item= activity.owner

app/views/home/index.html.haml
.card-group
  .card.card-body
    %h1
      .fa.fa-graduation-cap
    = Course.count
    online courses
    .row
    Explore a variety of fresh topics

  .card.card-body
    %h1
      .fa.fa-chalkboard-teacher
      /.fa.fa-brain
    = Course.distinct.count(:user_id)
    expert instructors
    .row
    Find the right instructor for you

  .card.card-body
    %h1
      .fa.fa-user-graduate
    = User.count
    active learners
    .row
    Join the knowledge sharing community

  .card.card-body
    %h1
      .fa.fa-infinity
    Lifetime access
    .row
    Learn on your schedule

%h1
  Popular courses
.row.row-cols-1-row-cols-md-3.g-4
  - @courses.each do |course|
    .col-4
      = render 'courses/course', course: course
%hr
%h1
  Top rated courses
.row.row-cols-1-row-cols-md-3.g-4
  - @courses.each do |course|
    .col-4
      = render 'courses/course', course: course
%hr
%h1
  Most recent courses
.row.row-cols-1-row-cols-md-3.g-4
  - @latest_courses.each do |course|
    .col-4
      = render 'courses/course', course: course

app/views/layouts/_footer.html.haml
%hr
%footer
  .container
    .row
      .col-md-4
        Copyright
        @
        = Time.now.year
        CoursePlatform Sp. z o.o.
        .row
        .fa.fa-envelope
        = mail_to 'yadolghintev@gmail.com'
        .row
      .col-md-4
        Privacy policy
        .row
        Terms and conditions
      .col-md-4
        About us
        .row
          = link_to 'Teach on EDURGE', new_course_path
%br

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container-fluid
    = link_to 'Rubygems', root_path, class: 'navbar-brand'
    %button.navbar-toggler{ 'aria-controls' => 'navbarSupportedContent', 'aria-expanded' => 'false', 'aria-label' => 'Toggle navigation', 'data-bs-target' => '#navbarSupportedContent', 'data-bs-toggle' => 'collapse', :type => 'button' }
      %span.navbar-toggler-icon.collapse.navbar-collapse#navbar-supported-content
    - if current_user
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          = link_to root_path, class: "nav-link #{'active' if current_page?(root_path)}" do
            .fa.fa-home
            Home
        %li.nav-item
          = link_to courses_path, class: "nav-link #{'active' if current_page?(courses_path)}" do
            .fa.fa-graduation-cap
            Courses
        %li.nav-item
          = link_to users_path, class: "nav-link #{'active' if current_page?(users_path)}" do
            .fa.fa-user
            Users
        %li.nav-item
          = link_to home_activity_path, class: "nav-link #{'active' if current_page?(home_activity_path)}" do
            .fa.fa-bell
            Activity
        %li.nav-item
          = link_to new_course_path, class: "nav-link #{'active' if current_page?(new_course_path)}" do
            .fa.fa-plus
            New Course
      %form.d-flex
        = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
          = f.search_field :title_cont, class: 'form-control me-2'
        %ul.navbar-nav
          %li.nav-item.dropdown
            %a.nav-link.dropdown-toggle#navbar-dropdown{ 'aria-expanded' => 'false', 'data-bs-toggle' => 'dropdown', href: '#', role: 'button' }
              = current_user.email
            %ul.dropdown-menu{ 'aria-labelledby' => 'navbar-dropdown' }
              %li
                %a.dropdown-item{ href: '#' } Action
                = link_to 'Accout settings', edit_user_registration_path, class: 'dropdown-item'
              %li
                = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item'
    - else
      %ul.navbar-nav
        %li.nav-item
          = link_to 'Sign up', new_user_registration_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Log in', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{ class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} fade show alert-dismissible", role: 'alert' }
      %button.btn-close{ 'aria-hidden' => 'true', 'data-bs-dismiss' => 'alert', :type => 'button' }
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title GemsBootcamp
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container-fluid
      %p
        = yield
    = render 'layouts/footer'

app/views/lessons/_form.html.haml
= simple_form_for(@lesson) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :content
    = f.rich_text_area :content
    = f.association :course, input_html: { hidden: true }

  .form-actions
    = f.button :submit

app/views/lessons/_lesson.html.haml
.card
  .card-header
    = link_to lesson.title, lesson
  - if policy(lesson).show?
    .card-body
      = lesson.content
      = lesson.course
  - if policy(lesson).edit?
    .card-footer
      = link_to 'Edit', edit_lesson_path(lesson), class: 'btn btn-secondary'
      = link_to 'Destory', lesson,
        method: :delete,
        data: { confirm: 'Are you sure?' },
        class: 'btn btn-danger'

app/views/lessons/edit.html.haml
%h1 Editing lesson

= render 'form'

= link_to 'Show', @lesson
\|
= link_to 'Back', lessons_path

app/views/lessons/index.html.haml
%h1 Listing lessons

%table
  %thead
    %tr
      %th Title
      %th Content
      %th Course
      %th
      %th
      %th

  %tbody
    - @lessons.each do |lesson|
      %tr
        %td= lesson.title
        %td= lesson.content
        %td= lesson.course
        %td= link_to 'Show', lesson
        %td= link_to 'Edit', edit_lesson_path(lesson)
        %td= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Lesson', new_lesson_path

app/views/lessons/new.html.haml
%h1 New lesson

= render 'form', course: @course

= link_to 'Back', lessons_path

app/views/lessons/show.html.haml
= link_to 'Lessons', lessons_path
\/
= link_to @lesson.title, lesson_path(@lesson)

= render 'lessons/lesson', lesson: @lesson

= link_to 'Back to course', course_path(@lesson.course)

app/views/users/_user.html.haml
.card
  .card-header
    .fa.fa-user
    = user.email
    - if user.online?
      .text-success.fa.fa-circle
  .card-footer
    Signed up
    - time_ago_in_words(user.created_at)
    ago
  .card-footer
    = user.sign_in_count
    = user.current_sign_in_at
    = user.last_sign_in_at
    = user.current_sign_in_ip
    = user.last_sign_in_ip
  .card-footer
    Confirmed email?
    - if user.confirmed_at.present?
      .badge.bg-success Yes
    - else
      .badge.bg-danger No

app/views/users/edit.html.haml
.card
  .card-header
    Editing roles for
    = @user.email
  .card-body
    = simple_form_for @user do |f|
      = f.collection_check_boxes :role_ids, Role.all, :id, :name
      = f.error :roles, class: 'text-danger'
      %hr
      = f.button :submit, class: 'btn btn-success'
  .card-footer
    = link_to 'Cancel', users_path, class: 'btn btn-danger'

app/views/users/index.html.haml
%h3
  .text-center.m-3
    Users
    .badge.bg-danger
      = @users.count

= search_form_for @q do |f|
  = f.search_field :email_cont, placeholder: 'email'
  = f.search_field :sign_in_count_eq, placeholder: 'sign in count'
  = f.submit
= link_to users_path, class: 'btn btn-secondary' do
  .fa.fa-sync

%table.table.table-bordered
  %thead
    %tr
      %th= 'id'.humanize
      %th= sort_link(@q, :email)
      %th= 'created_at'.humanize
      %th= 'sign_in_count'.humanize
      %th= 'current_sign_in_at'.humanize
      %th= 'last_sign_in_at'.humanize
      %th= 'current_sign_in_ip'.humanize
      %th= 'last_sign_in_ip'.humanize
      %th= 'roles'.humanize
      %th= 'actions'.humanize
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td
          = link_to user.email, user_path(user)
        %td= user.created_at
        %td= user.sign_in_count
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip
        %td
          - user.roles.map do |role|
            .badge.bg-info
              = role.name
        %td
          = link_to 'Edit roles', edit_user_path(user), class: 'btn btn-secondary'

app/views/users/show.html.haml
= render 'users/user', user: @user